### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [pipe-felipe/zsh-pipe-plugin#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by pipe-felipe** [comment]
Thank you for considering my plugin for awesome-zsh-plugins. I apologize for the oversight of not including a license file. I have now added a license file to the plugin and have chosen the MIT license. Please let me know if there are any further concerns or issues. Thank you again for your interest in my plugin
